
GET http://localhost:3000/tweets

###
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "User": {
        "Name": "Wallisson Marinho"
    },
    "Text": "LinkedIn https://www.linkedin.com/in/wallissonmarinho/"
}

###
GET http://localhost:3000/mail-list


###
POST http://localhost:3000/mail-list
Content-Type: application/json

{
    "emails": [
        "wallissonsmarinho@gmail.com",
        "wallissonmarinho@hotmail.com",
        "teste@mail.com"
    ]
}