
GET http://localhost:3000/tweets

###
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "User": {
        "Name": "Wallisson Marinho"
    },
    "Text": "LinkedIn https://www.linkedin.com/in/wallissonmarinho/"
}